name: Test bda.plone.shop

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
        plone:
          - "6.0-latest"

    steps:
      - uses: actions/checkout@v4

      - name: Setup Plone ${{ matrix.plone }} with Python ${{ matrix.python }}
        id: setup
        uses: plone/setup-plone@v2.0.0
        with:
          python-version: ${{ matrix.python }}
          plone-version: ${{ matrix.plone }}
          setuptools-version: 69.5.1
          additional-eggs: 'setuptools'

      - name: Install package
        run: |
          make install

      - name: Run Lint
        run: |
          make check

      - name: Run Tests
        run: |
          make test
